controller_list:
  - name: fake_scaled_pos_joint_traj_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - rg2_gripper_finger_left_joint
initial:  # Define initial robot poses per group
  - group: ur_manipulator
    pose: home
  - group: gripper
    pose: close